### ISSUE TITLE
Beta checklist

### ISSUE THREAD

**Issue by a15n** [a15n/equidate-share-prices#1]
TODOs 
- [ ] make the Selemium scraper less brittle by adding failsafes and depending on xpath less
- [ ] remove `webdriver.Chrome(r"/Users/sadiewilliams/andrew/chromedriver")` maybe using venv?
- [ ] manually run the script on each Tuesday until we can set up a Chron job and a DB
- [ ] once we have enough data points build out a front end using Highcharts

**Comment by tjont** [comment]
that second one (remove `webdriver.Chrome(...)` might be doable by installing the chrome webdriver via homebrew, at least according to http://stackoverflow.com/a/8946843
